apiVersion: v1
kind: ConfigMap
metadata:
  name: student-app-config
  namespace: {{ .Values.namespace.name }}
data:
  DB_URL: {{ .Values.config.dbUrl | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
